# Header

menu:
  主页: /
  随笔: /tags/daily
  觅食: /tags/food

# SubNav
subnav:
  github: "https://github.com/quqinjiayou"
  weibo: "http://weibo.com/quqinjiayou"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /images/avatar.jpg

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  tagcloud: '标签'
  friends: '友链'
  aboutme: '关于我'

friends:
  前端小伙儿杨buss: http://kunsun.me/

aboutme:
  研究生方向自然语言处理<br>但强项是说自然语言<br>喜欢写点小代码但技术很渣<br><br>很贪心<br>工作生活爱情友情都要<br>还有洒在工作台的阳光